version: 2

jobs:
  python-2.7: &test-template
    docker:
      - image: circleci/python:2.7-stretch-node-browsers
        environment:
          PYTHON_VERSION: py27
          PERCY_ENABLE: 1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Write job name
          command: echo $CIRCLE_JOB > circlejob.txt

      - run:
          name: Install dependencies
          command: |
              sudo pip install virtualenv --upgrade
              python -m venv venv || virtualenv venv
              . venv/bin/activate
              pip install -r dev-requirements.txt
              npm install --ignore-scripts

      - run:
          name: Install dependencies (dash)
          command: |
              git clone --depth 1 git@github.com:plotly/dash.git dash-main
              git clone --depth 1 git@github.com:plotly/dash-core-components.git
              git clone --depth 1 git@github.com:plotly/dash-table.git
              . venv/bin/activate
              pip install -e ./dash-main[testing,dev] --quiet
              cd dash-core-components && npm install --ignore-scripts && npm run build && pip install -e . && cd ..
              cd dash-main/dash-renderer && npm run build && pip install -e . && cd ../..
              cd dash-table && npm install --ignore-scripts && npm run build && pip install -e . && cd ..

      - run:
          name: Build
          command: |
              . venv/bin/activate
              python --version
              npm run clean
              npm run build

      - run:
          name: Run tests
          command: |
              . venv/bin/activate
              python --version
              npm run test

  python-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6-stretch-node-browsers
        environment:
          PYTHON_VERSION: py36
          PERCY_ENABLE: 0

  python-3.7:
    <<: *test-template
    docker:
      - image: circleci/python:3.7-stretch-node-browsers
        environment:
          PYTHON_VERSION: py37
          PERCY_ENABLE: 0

workflows:
  version: 2
  build:
    jobs:
      - python-2.7
      - python-3.6
      - python-3.7
