version: 2

jobs:
  "python-2.7": &test-template
    docker:
      - image: circleci/python:2.7-stretch-node-browsers
        environment:
          PYTHON_VERSION: py27

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Write job name
          command: echo $CIRCLE_JOB > circlejob.txt

      - run:
          name: Create venv
          command: |
              sudo pip install virtualenv --upgrade
              python -m venv venv || virtualenv venv

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "circlejob.txt" }}

      - run:
          name: Install dependencies
          command: |
              . venv/bin/activate
              pip install -r requirements.txt
              npm install --ignore-scripts

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "circlejob.txt" }}
          paths:
              - "venv"
              - "node_modules"

      - run:
          name: Build
          command: |
              . venv/bin/activate
              npm run clean
              npm run generate-components
              npm run build:js
              npm run build:py
              npm run generate-python-classes

      - run:
          name: Run tests
          command: |
              npm run test
              . venv/bin/activate
              python --version
              python -m unittest tests.test_dash_html_components
              python -m unittest tests.test_integration
              python -m unittest tests.test_dash_import

  "python-3.6":
    <<: *test-template
    docker:
      - image: circleci/python:3.6-stretch-node-browsers
        environment:
          PYTHON_VERSION: py36

  "python-3.7":
    <<: *test-template
    docker:
      - image: circleci/python:3.7-stretch-node-browsers
        environment:
          PYTHON_VERSION: py37

workflows:
  version: 2
  build:
    jobs:
      - "python-2.7"
      - "python-3.6"
