version: 2

jobs:
    "server-test":
        docker:
            - image: circleci/python:3.6.7-node-browsers
            - image: cypress/base:10

        steps:
            - checkout
            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}
            - run:
                name: Install npm packages
                command: npm install
            - run:
                name: Cypress Install
                command: |
                    $(npm bin)/cypress install

            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}
                paths:
                    - node_modules
                    - /home/circleci/.cache/Cypress

            - run:
                name: Install requirements
                command: |
                    sudo pip install --upgrade virtualenv
                    python -m venv venv || virtualenv venv
                    . venv/bin/activate
                    pip install -r dev-requirements.txt --quiet
                    git clone --depth 1 -b exp-dynamic git@github.com:plotly/dash.git dash-main
                    pip install -e ./dash-main[dev] --quiet

            - run:
                name: Build
                command: |
                    . venv/bin/activate
                    npm run private::build:js-test
                    npm run private::build:py
                    pip install -e .

            - run:
                name: Run tests
                command: |
                    . venv/bin/activate
                    npm run test.server


    "standalone-test":
        docker:
            - image: circleci/python:3.6.7-node-browsers
            - image: cypress/base:10

        steps:
            - checkout
            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}
            - run:
                name: Install npm packages
                command: npm install
            - run:
                name: Cypress Install
                command: |
                    $(npm bin)/cypress install

            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}
                paths:
                    - node_modules
                    - /home/circleci/.cache/Cypress

            - run:
                name: Run tests
                command: npm run test.standalone


    "unit-test":
        docker:
            - image: circleci/python:3.6.7-node-browsers
            - image: cypress/base:10

        steps:
            - checkout
            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}
            - run:
                name: Install npm packages
                command: npm install
            - run:
                name: Cypress Install
                command: |
                    $(npm bin)/cypress install

            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}
                paths:
                    - node_modules
                    - /home/circleci/.cache/Cypress

            - run:
                name: Install requirements
                command: |
                    sudo pip install --upgrade virtualenv
                    python -m venv venv || virtualenv venv
                    . venv/bin/activate
                    pip install -r dev-requirements.txt --quiet
                    git clone --depth 1 -b exp-dynamic git@github.com:plotly/dash.git dash-main
                    pip install -e ./dash-main[dev] --quiet

            - run:
                name: Run tests
                command: |
                    . venv/bin/activate
                    npm run build
                    npm run test.unit


    "visual-test":
        docker:
            - image: circleci/node:8.11.3-browsers

        steps:
            - checkout

            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}

            - run:
                name: Install package.json
                command: npm i

            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
                paths:
                    - node_modules

            - run:
                name: Run build:js
                command: npm run private::build:js

            - run:
                name: Run visual tests
                command: npm run test.visual


    "node":
        docker:
            - image: circleci/python:3.6.7-node

        steps:
            - checkout

            - run:
                  name: Create virtual env
                  command: python -m venv || virtualenv venv

            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}

            - run:
                name: Install package.json
                command: npm i

            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
                paths:
                    - node_modules

            - run:
                name: Install requirements
                command: |
                    . venv/bin/activate
                    pip install -r dev-requirements.txt --quiet

            - run:
                name: Run eslint
                command: |
                    . venv/bin/activate
                    npm run lint
                when: always


    "python-3.6":
        docker:
            - image: circleci/python:3.6.7-stretch-node-browsers

        environment:
            PERCY_ENABLED: True
            PERCY_PROJECT: plotly/dash-table-python-v0

        steps:
            - checkout

            - run:
                name: Inject Percy Environment variables
                command: |
                  echo 'export PERCY_TOKEN="$PERCY_PYTHON_TOKEN_V0"' >> $BASH_ENV

            - run:
                name: Install requirements
                command: |
                    sudo pip install --upgrade virtualenv
                    python -m venv venv || virtualenv venv
                    . venv/bin/activate
                    pip install -r dev-requirements.txt --quiet
                    npm install

            - run:
                name: Install dependencies (dash)
                command: |
                    . venv/bin/activate
                    git clone --depth 1 -b exp-dynamic git@github.com:plotly/dash.git dash-main
                    pip install -e ./dash-main[dev,testing] --quiet
                    cd dash-main/dash-renderer && npm run build && pip install -e . && cd ../..

            - run:
                name: Install test requirements
                command: |
                    . venv/bin/activate
                    npm run build
                    pip install -e .

            - run:
                name: ⚙️ run integration test
                command: |
                  . venv/bin/activate
                  pytest --junitxml=test-reports/dash.xml tests/integration
            - store_artifacts:
                path: test-reports
            - store_test_results:
                path: test-reports
            - store_artifacts:
                path: /tmp/dash_artifacts



workflows:
    version: 2
    build:
        jobs:
            - "python-3.6"
            - "node"
            - "server-test"
            - "standalone-test"
            - "unit-test"
            - "visual-test"
