version: 2

jobs:
    "test":
        docker:
            - image: circleci/python:3.6-node-browsers
            - image: cypress/base:8

        steps:
            - checkout
            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "npm-shrinkwrap.json" }}-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}
            - run:
                name: Install npm packages
                command: npm install
            - run:
                name: Cypress Install
                command: |
                    $(npm bin)/cypress install

            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "npm-shrinkwrap.json" }}-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}
                paths:
                    - node_modules
                    - /home/circleci/.cache/Cypress

            - run:
                name: Create virtualenv
                command: |
                    python3 -m venv venv

            - run:
                name: Install requirements
                command: |
                    . venv/bin/activate
                    pip install -r tests/python_fixtures/requirements.txt --quiet

            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "tests/python_fixtures/requirements.txt" }}
                paths:
                    - "venv"

            - run:
                name: Run build:js
                command: npm run build:js

            - run:
                name: Run build:py
                command: npm run build:py

            - run:
                name: Run hosts
                command: |
                    . venv/bin/activate
                    npm run test

    "node":
        docker:
            - image: circleci/node:8.11.3

        steps:
            - checkout

            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "npm-shrinkwrap.json" }}-{{ checksum "package.json" }}

            - run:
                name: Install package.json
                command: npm i

            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "npm-shrinkwrap.json" }}-{{ checksum "package.json" }}
                paths:
                    - node_modules

            - run:
                name: Run eslint
                command: npm run lint
                when: always


    "python-3.6":
        docker:
            - image: circleci/python:3.6-stretch-browsers

        environment:
            PERCY_ENABLED: False

        steps:
            - checkout

            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "tests/requirements.txt" }}

            - run:
                name: Create virtualenv
                command: |
                    python3 -m venv venv

            - run:
                name: Install requirements
                command: |
                    . venv/bin/activate
                    pip install -r tests/python_fixtures/requirements.txt --quiet

            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "tests/python_fixtures/requirements.txt" }}
                paths:
                    - "venv"

            - run:
                name: Run pylint
                command: |
                    . venv/bin/activate
                    pylint usage.py tests
                when: always

            - run:
                name: Run flake8
                command: |
                    . venv/bin/activate
                    flake8 usage.py tests
                when: always

            - run:
                name: Integration Tests
                command: |
                    . venv/bin/activate
                    python -m unittest tests.python_fixtures.test_render
                when: always


workflows:
    version: 2
    build:
        jobs:
            - "python-3.6"
            - "node"
            - "test"
