version: 2

jobs:
    "test":
        docker:
            - image: circleci/python:3.6-node-browsers
            - image: cypress/base:10

        steps:
            - checkout
            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "npm-shrinkwrap.json" }}-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}
            - run:
                name: Install npm packages
                command: npm install
            - run:
                name: Cypress Install
                command: |
                    $(npm bin)/cypress install

            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "npm-shrinkwrap.json" }}-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}
                paths:
                    - node_modules
                    - /home/circleci/.cache/Cypress

            - run:
                name: Create virtualenv
                command: |
                    python3 -m venv venv

            - run:
                name: Install requirements
                command: |
                    . venv/bin/activate
                    pip install -r requirements.txt --quiet

            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
                paths:
                    - "venv"

            - run:
                name: Run build:js
                command: npm run private::build:js-test

            - run:
                name: Run build:py
                command: |
                    . venv/bin/activate
                    npm run private::build:py

            - run:
                name: Run tests
                command: |
                    . venv/bin/activate
                    npm run test


    "visual-test":
        docker:
            - image: circleci/node:8.11.3-browsers

        steps:
            - checkout

            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "npm-shrinkwrap.json" }}-{{ checksum "package.json" }}

            - run:
                name: Install package.json
                command: npm i

            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "npm-shrinkwrap.json" }}-{{ checksum "package.json" }}
                paths:
                    - node_modules

            - run:
                name: Run build:js
                command: npm run private::build:js

            - run:
                name: Run visual tests
                command: npm run test.visual


    "node":
        docker:
            - image: circleci/node:8.11.3

        steps:
            - checkout

            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "npm-shrinkwrap.json" }}-{{ checksum "package.json" }}

            - run:
                name: Install package.json
                command: npm i

            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "npm-shrinkwrap.json" }}-{{ checksum "package.json" }}
                paths:
                    - node_modules

            - run:
                name: Run eslint
                command: npm run lint
                when: always


    "python-3.6":
        docker:
            - image: circleci/python:3.6-stretch-browsers

        environment:
            PERCY_ENABLED: True
            PERCY_PROJECT: plotly/dash-table-python

        steps:
            - checkout

            - run:
                name: Inject Percy Environment variables
                command: |
                  echo 'export PERCY_TOKEN="$PERCY_PYTHON_TOKEN"' >> $BASH_ENV

            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

            - run:
                name: Create virtualenv
                command: |
                    python3 -m venv venv

            - run:
                name: Install requirements
                command: |
                    . venv/bin/activate
                    pip install -r requirements.txt --quiet

            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
                paths:
                    - "venv"

            - run:
                name: Run integration tests
                command: |
                  . venv/bin/activate
                  python -m unittest tests.dash.test_integration



workflows:
    version: 2
    build:
        jobs:
            - "python-3.6"
            - "node"
            - "test"
            - "visual-test"
