version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  dcc-percy-finalize:
    working_directory: ~/dash/components/dash-core-components
    docker:
      - image: percyio/agent
        auth:
          username: dashautomation
          password: $DASH_PAT_DOCKERHUB
    steps:
      - run: percy finalize --all

  dcc-lint-unit-39: &lint-unit
    working_directory: ~/dash/components/dash-core-components
    docker:
      - image: circleci/python:3.9.2-buster-node-browsers
        auth:
          username: dashautomation
          password: $DASH_PAT_DOCKERHUB
        environment:
          PYTHON_VERSION: py39
    steps:
      - checkout
      - run: echo $PYTHON_VERSION > ver.txt
      - restore_cache:
          key: dep-{{ checksum ".circleci/config.yml" }}-{{ checksum "ver.txt" }}-{{ checksum "dev-requirements.txt" }}
      - run:
          name: ğŸ pip dev requirements
          command: |
            sudo pip install virtualenv --upgrade
            python -m venv venv || virtualenv venv && . venv/bin/activate
            pip install --progress-bar off -e git+https://github.com/plotly/dash.git@dev#egg=dash[dev,testing]
            cd components/dash-core-components && pip install --progress-bar off --no-cache-dir -r dev-requirements.txt
      - save_cache:
          key: dep-{{ checksum ".circleci/config.yml" }}-{{ checksum "ver.txt" }}-{{ checksum "dev-requirements.txt" }}
          paths:
              - venv
      - run:
          name: ğŸŒ¸ Lint
          command: |
            cd components/dash-core-components
            . venv/bin/activate
            set -eo pipefail
            npm ci
            npm run lint

  dcc-lint-unit-36:
    <<: *lint-unit
    docker:
      - image: circleci/python:3.6.13-stretch-node-browsers
        auth:
          username: dashautomation
          password: $DASH_PAT_DOCKERHUB
        environment:
          PYTHON_VERSION: py36

  dcc-lint-unit-27:
    <<: *lint-unit
    docker:
      - image: circleci/python:2.7.18-stretch-node-browsers
        auth:
          username: dashautomation
          password: $DASH_PAT_DOCKERHUB
        environment:
          PYTHON_VERSION: py27

  dcc-build-dash-39: &build-dash
    working_directory: ~/dash/components/dash-core-components
    docker:
      - image: circleci/python:3.9.2-buster-node-browsers
        auth:
          username: dashautomation
          password: $DASH_PAT_DOCKERHUB
        environment:
            PYTHON_VERSION: py39
    steps:
      - checkout
      - run: echo $PYTHON_VERSION > ver.txt
      - restore_cache:
          key: dep-{{ checksum ".circleci/config.yml" }}-{{ checksum "ver.txt" }}-{{ checksum "dev-requirements.txt" }}
      - run:
          name: ğŸ pip dev requirements
          command: |
            sudo pip install virtualenv --upgrade
            python -m venv venv || virtualenv venv && . venv/bin/activate
            set -eo pipefail
            cd components/dash-core-components && pip install --progress-bar off --no-cache-dir -r dev-requirements.txt
      - save_cache:
          key: dep-{{ checksum ".circleci/config.yml" }}-{{ checksum "ver.txt" }}-{{ checksum "dev-requirements.txt" }}
          paths:
              - venv
      - run:
          name: ğŸ—ï¸ build dash
          command: |
            cd components/dash-core-components
            . venv/bin/activate && mkdir packages
            set -eo pipefail
            # build main dash & renderer
            git clone --depth 1 https://github.com/plotly/dash.git dash-main
            cd dash-main && pip install -e .[dev] --progress-bar off && renderer build
            python setup.py sdist && mv dist/* ../packages/ && cd ..
            # build html
            git clone --depth 1 https://github.com/plotly/dash-html-components.git
            cd dash-html-components && npm ci && npm run build
            python setup.py sdist && mv dist/* ../packages && cd ..
            # build dcc
            npm ci && npm run build && python setup.py sdist && mv dist/* ./packages && ls -la packages
      - persist_to_workspace:
          root: ~/project
          paths:
            - packages

  dcc-build-dash-36:
    <<: *build-dash
    docker:
      - image: circleci/python:3.6.13-stretch-node-browsers
        auth:
          username: dashautomation
          password: $DASH_PAT_DOCKERHUB
        environment:
          PYTHON_VERSION: py36

  dcc-build-dash-27:
    <<: *build-dash
    docker:
      - image: circleci/python:2.7.18-stretch-node-browsers
        auth:
          username: dashautomation
          password: $DASH_PAT_DOCKERHUB
        environment:
          PYTHON_VERSION: py27

  dcc-test-39: &test
    working_directory: ~/dash/components/dash-core-components
    docker:
      - image: circleci/python:3.9.2-buster-node-browsers
        auth:
          username: dashautomation
          password: $DASH_PAT_DOCKERHUB
        environment:
            PYTHON_VERSION: py39
            PERCY_PARALLEL_TOTAL: -1
            PERCY_ENABLE: 1
    parallelism: 3
    steps:
      - checkout
      - run: echo $PYTHON_VERSION > ver.txt
      - restore_cache:
          key: dep-{{ checksum ".circleci/config.yml" }}-{{ checksum "ver.txt" }}-{{ checksum "dev-requirements.txt" }}
      - attach_workspace:
          at: ~/project
      - run:
          name: ğŸ§ª Run Integration Tests
          command: |
            cd components/dash-core-components
            . venv/bin/activate && rm -rf dash_core_components && ls -la
            set -eo pipefail
            cd packages && mv dash-*.tar.gz main.tar.gz && ls -la
            find . -name "dash_*.gz" | xargs pip install -I --progress-bar off --no-cache-dir
            pip install --no-cache-dir --progress-bar off main.tar.gz[dev,testing]
            pip list | grep dash | xargs pip show && cd ..
            echo $(python -V 2>&1) | grep 3. && python -m unittest tests/test_dash_import.py
            TESTFILES=$(circleci tests glob "tests/integration/**/test_*.py" | circleci tests split --split-by=timings)
            pytest --headless --nopercyfinalize --junitxml=test-reports/junit_intg.xml ${TESTFILES}
      - store_artifacts:
          path: test-reports
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: /tmp/dash_artifacts

  dcc-test-36:
    <<: *test
    docker:
      - image: circleci/python:3.6.13-stretch-node-browsers
        auth:
          username: dashautomation
          password: $DASH_PAT_DOCKERHUB
        environment:
          PYTHON_VERSION: py36
          PERCY_ENABLE: 0

  dcc-test-27:
    <<: *test
    docker:
      - image: circleci/python:2.7.18-stretch-node-browsers
        auth:
          username: dashautomation
          password: $DASH_PAT_DOCKERHUB
        environment:
          PYTHON_VERSION: py27
          PERCY_ENABLE: 0

workflows:
  dcc-python3.9:
    jobs:
      - dcc-lint-unit-39
      - dcc-build-dash-39
      - dcc-test-39:
          requires:
            - dcc-build-dash-39
      - dcc-percy-finalize:
          requires:
            - dcc-test-39

  dcc-python3.6:
    jobs:
      - dcc-lint-unit-36
      - dcc-build-dash-36
      - dcc-test-36:
          requires:
            - dcc-build-dash-36

  dcc-python2.7:
    jobs:
      - dcc-lint-unit-27
      - dcc-build-dash-27
      - dcc-test-27:
          requires:
            - dcc-build-dash-27
